services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/energydb
      SPRING_DATASOURCE_USERNAME: energy
      SPRING_DATASOURCE_PASSWORD: energy
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8080
    ports:
      - "5173:5173"
